export const sourceDimensions = {
  topNavHeight: 56,
  crmSideWidth: 210,
  pagePadding: '20px 20px 0',
  pageHeaderPaddingBottom: 16,
  searchInputWidth: 220,
  filterHeaderPaddingBottom: 16,
  maxVisibleSceneCount: 8,
  viewToggleItemSize: 24,
  fixedColumnWidth: 40,
  tableRowHeight: 32,
  tableHeaderPadding: '4px 0',
  tableMinHeight: 320,
  tableStaticOffset: 206,
  paginationHeight: 64,
  stageViewExtraHeight: 64,
  selectionBarHeight: 48,
  selectionCheckboxMargin: '0 20px',
  selectionOperationPaddingX: 15,
  createDialogWidth: 900,
  createPaddingY: 40,
  createCardHeightOffset: 80,
  createRadius: 16,
  createHeaderHeight: 50,
  createInputHeight: 32,
  smallDialogWidth: 450,
  slideMinWidth: 950,
  slideVisibleListWidth: 160,
  detailCloseTop: 160,
  detailCloseLeft: -40,
  detailClosePaddingY: 19,
  detailClosePaddingX: 6,
  detailCloseIconSize: 26,
  detailMenuRowHeight: 41,
  detailMenuItemHeight: 25,
  detailMenuItemMinWidth: 96,
  detailMenuDotSize: 8,
  detailMenuLineRight: 8.5,
  detailRightWidth: 340,
  detailRightMinWidth: 330,
  detailRightCollapsedWidth: 40,
  detailControlsTop: 160,
  detailStageItemHeight: 22,
  detailValueBoxHeight: 32,
  detailBaseItemMinHeight: 24,
  detailSectionHeaderHeight: 48,
  adminSidebarWidth: 210,
  adminMenuRowHeight: 40,
  adminLocalNavWidth: 240,
  adminDepartmentTreeNodeHeight: 40,
  adminEmployeeTableOffset: 290,
  adminRoleTableOffset: 300,
  adminRoleTreeOffset: 230,
  adminFieldDesignerLeftWidth: 280,
  adminFieldDesignerCanvasWidth: 900,
  adminFieldDesignerRightWidth: 280,
  adminFieldEntryTableOffset: 155,
  adminApprovalTableOffset: 220,
  adminLogTableOffset: 270,
  adminBizParamTableOffset: 344,
  adminBizParamLimitTableOffset: 290,
  adminPoolActionColumnWidth: 200,
  adminPrintActionColumnWidth: 250,
  adminLogDetailDialogWidth: 700,
  adminFlowTabsHeight: 60,
  adminFlowBaseInfoWidth: 900
}

export const sourceColors = {
  primary: '#0052CC',
  success: '#00875A',
  warning: '#FF991F',
  danger: '#DE350B',
  info: '#5243AA',
  topNav: '#FFFFFF',
  adminSidebarBackground: '#F6F8FB',
  pageBackground: '#F5F6F9',
  tableHeaderBackground: '#DFE1E6',
  tableHeaderText: '#787D97',
  selectionBarBackground: '#42526E',
  detailBackground: '#F4F9FC'
}

export const sourceFontWeights = {
  tableHeader: 500,
  tableBody: 400,
  primaryLink: 500,
  selectionTitle: 600
}

export const sourceSchemaContract = {
  schemaVersion: 'p5.1',
  crmObjectTypes: ['customer', 'leads', 'contacts', 'business', 'contract'],
  adminModuleKeys: ['employeeDepartment', 'rolePermission', 'customField', 'approvalFlow', 'leadsPoolRule', 'customerPoolRule', 'printTemplate', 'businessParam', 'systemLog'],
  requiredCrmTemplateKeys: [
    'type',
    'moduleName',
    'title',
    'mainField',
    'idField',
    'searchPlaceholder',
    'sceneList',
    'fieldList',
    'rows',
    'stageFlow',
    'cardRows',
    'createFieldGroups',
    'detailTabs',
    'detailData',
    'operations'
  ],
  requiredCrmFieldKeys: [
    'prop',
    'field',
    'label',
    'name',
    'formType',
    'width',
    'stylePercent',
    'isNull',
    'placeholder',
    'setting',
    'tableVisible',
    'createVisible',
    'detailVisible',
    'mockValue'
  ],
  requiredAdminModuleKeys: [
    'title',
    'navKey',
    'filters',
    'fields',
    'rows',
    'actions',
    'dialogs',
    'layout'
  ]
}

export const sourceSelectors = {
  tableHeaderRoot: '.wk-table-header',
  topNav: '[data-section="crm-top-nav"]',
  crmSide: '.crm-side',
  crmPage: '.app-container.crm-page',
  pageHeader: '.wk-page-header',
  pageHeaderCreate: '.wk-page-header__right .el-button--primary',
  searchInput: '.wk-filter-header .search-input',
  filterRight: '.wk-filter-header .filter-right',
  viewToggleItem: '.wk-toggle-item',
  selectionBar: '.selection-bar',
  selectionCheckbox: '.selection-check',
  selectedTitle: '.selected-title',
  selectedCount: '.selected-count',
  selectionClear: '.clear',
  selectionItem: '.selection-item',
  sourceTable: '.crm-source-table',
  tableHeaderCell: '.crm-source-table th.el-table__cell',
  tableBodyRow: '.crm-source-table .el-table__row',
  tableBodyCell: '.crm-source-table td.el-table__cell',
  fixedSelectionCell: '.crm-source-table .el-table__header-wrapper .el-table-column--selection',
  fixedCallCell: '.crm-source-table .el-table__header-wrapper th:nth-child(2)',
  fixedStarCell: '.crm-source-table .el-table__header-wrapper th:nth-child(3)',
  primaryLink: '.crm-source-table .can-visit--underline',
  businessIcon: '.crm-source-table .wk-business',
  pagination: '.p-contianer',
  stageView: '.stage-view',
  cardContainer: '.card-container',
  createView: '.create-view',
  createCard: '.create-view-content',
  createHeader: '.xr-create__header',
  createTitle: '.xr-create__header .title',
  createBody: '.xr-create__body',
  createFooter: '.xr-create__footer',
  createSection: '.create-sections',
  createSectionTitle: '.create-sections .section-title',
  createForm: '.xr-create__body .wk-form',
  createFormItems: '.xr-create__body .wk-form-items',
  createFormItem: '.xr-create__body .wk-form-item:not(.is-data_collapse)',
  createInput: '.xr-create__body .wk-form-item .el-input__wrapper',
  createBusinessInfo: '.wk-premium-info-btn',
  createCollapse: '.wk-field-collapse',
  putPoolDialog: '.el-dialog[aria-label="放入公海"]',
  detailSlide: '.slide-detail-card-container',
  detailClose: '.slide-detail-card-container .close-btn',
  detailMenu: '.wmd-tabs',
  detailMenuLayout: '.wk-menu-detail',
  detailMenuRow: '.wk-menu-detail .el-tabs__item.is-left',
  detailMenuItem: '.wk-menu-detail .wmd-menu',
  detailMenuNav: '.wk-menu-detail .el-tabs__nav.is-left',
  detailContainer: '.container-wrapper',
  detailContent: '.wmd-content',
  detailMain: '.wmd-main',
  detailBody: '.wmd-body',
  detailRight: '.wmd-right',
  detailControls: '.wmd-controls',
  detailHeaderCard: '.wmd-header',
  detailHeaderTitle: '.wk-detail-header-title',
  detailBase: '.detail-base',
  detailQuickCreate: '.wk-quick-create-trigger',
  detailStageCard: '.relative-stage-records',
  detailStageItem: '.relative-stage-records .stage-state-item',
  detailActivity: '[data-section="detail-activity"]',
  detailActivityTabs: '[data-section="detail-activity"] .activity-tabs',
  detailActivityInput: '[data-section="detail-activity"] .activity-input',
  detailFields: '[data-section="detail-fields"]',
  detailValueBox: '[data-section="detail-fields"] .value-box',
  detailContacts: '[data-section="detail-contacts"]',
  detailFiles: '[data-section="detail-files"]',
  detailLogs: '[data-section="detail-logs"]',
  detailSummary: '[data-section="detail-summary"]',
  detailSummaryHeader: '[data-section="detail-summary"] .section-head',
  detailSummaryItem: '[data-section="detail-summary"] .wk-section-item',
  detailSummaryValue: '[data-section="detail-summary"] .summary-value',
  adminManageEntry: '.top-tool--manage',
  adminAvatar: '.top-avatar',
  adminTopNav: '[data-section="admin-top-nav"]',
  adminTopModuleNav: '[data-section="admin-top-nav"] .new-header-menu',
  adminTopModuleItem: '[data-section="admin-top-nav"] .new-header-menu .el-tabs__item',
  adminTopActiveModule: '[data-section="admin-top-nav"] .new-header-menu .el-tabs__item.is-active .label',
  adminTopMessage: '[data-section="admin-top-nav"] .top-tool--message',
  adminTopManage: '[data-section="admin-top-nav"] .top-tool--manage',
  adminTopTools: '[data-section="admin-top-nav"] .admin-top-tools',
  adminShell: '[data-section="admin-shell"]',
  adminGlobalSide: '[data-section="admin-global-side"]',
  adminGlobalSideMain: '[data-section="admin-global-side"] .sidebar-container-main',
  adminMenuRow: '[data-section="admin-global-side"] .main-row',
  adminMenuIcon: '[data-section="admin-global-side"] .main-row__icon',
  adminSecondRow: '[data-section="admin-global-side"] .second-row',
  adminWorkspace: '[data-section="admin-workspace"]',
  adminEmployee: '[data-section="admin-employee"]',
  adminLocalNav: '[data-section="admin-local-nav"]',
  adminLocalNavContent: '[data-section="admin-local-nav"] .main-nav__content',
  adminDepartmentTreeWrap: '[data-section="admin-department-tree-wrap"]',
  adminCurrentDepartment: '[data-section="admin-local-nav"] .el-tree-node.is-current > .el-tree-node__content',
  adminEmployeeTableWrap: '[data-section="admin-employee-table-wrap"]',
  adminEmployeeTable: '[data-section="admin-employee"] .admin-source-table',
  adminDepartmentDialog: '[data-section="admin-department-dialog"]',
  adminRole: '[data-section="admin-role"]',
  adminRoleNav: '[data-section="admin-role-nav"]',
  adminRoleListWrap: '[data-section="admin-role-list-wrap"]',
  adminActiveRole: '[data-section="admin-role-nav"] .menu-item.is-select',
  adminRoleTable: '[data-section="admin-role"] .admin-source-table',
  adminRoleRange: '[data-section="admin-role-range"]',
  adminPermissionTree: '[data-section="admin-permission-tree"]',
  adminFieldAuthDialog: '[data-section="admin-field-auth-dialog"]',
  adminFieldDesigner: '[data-section="admin-field-designer"]',
  adminFieldLibrary: '[data-section="admin-field-library"]',
  adminFieldCanvas: '[data-section="admin-field-canvas"]',
  adminFieldSetting: '[data-section="admin-field-setting"]',
  adminApproval: '[data-section="admin-approval"]',
  adminApprovalTable: '[data-section="admin-approval"] .admin-source-table',
  adminFlowCreate: '[data-section="admin-flow-create"]',
  adminPoolRule: '[data-section="admin-pool-rule"]',
  adminConfigList: '[data-section="admin-config-list"]',
  adminBizParam: '[data-section="admin-biz-param"]',
  adminBizParamNav: '[data-section="admin-biz-param-nav"]',
  adminBizParamPanel: '[data-section="admin-biz-param-panel"]',
  adminLog: '[data-section="admin-log"]',
  adminLogFilter: '[data-section="admin-log-filter"]',
  adminLogTable: '[data-section="admin-log"] .admin-source-table',
  adminLogDetailDialog: '[data-section="admin-log-detail-dialog"]'
}

export function getSourceTableHeight(windowHeight, tableHeaderHeight) {
  // 源码列表用 206 扣除顶部导航、页面头、分页区和固定间距，最小高度避免窄屏表格塌陷。
  return Math.max(
    sourceDimensions.tableMinHeight,
    windowHeight - tableHeaderHeight - sourceDimensions.tableStaticOffset
  )
}
